Integrated Travis.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,18 +6,35 @@ on:
       - master
 
 jobs:
-  build:
+  lighthouse:
     runs-on: macos-latest
+    # steps:
+    #   - uses: actions/checkout@v1
+    #   - name: Audit URLs using Lighthouse
+    #     uses: treosh/lighthouse-ci-action@v2
+    #     with:
+    #       urls: |
+    #         https://treo.sh/
+    #         https://treo.sh/demo
+    #       temporaryPublicStorage: true
+    #       configPath: ./lighthouserc.yml
+    #   - name: Save results
+    #     uses: actions/upload-artifact@v1
+    #     with:
+    #       name: lighthouse-results
+    #       path: '.lighthouseci' # This will save the Lighthouse results as .json files
 
     steps:
-    - name: Run a multi-line script
-      run: |
-        echo Builded with NPM.
-        
-  audit:
-    runs-on: macos-latest
-    needs: [build]
-
-    steps:
-      - name: Google Lighthouse Audit
-        run: echo Audited with Lighthouse!
+      - uses: actions/checkout@v1
+      - name: Use Node.js 10.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 10.x
+      - name: npm install, build
+        run: |
+          npm install
+          npm run build
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
